# Generated by Django 2.0.1 on 2018-03-15 01:38

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('web_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discounts', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('image', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('web_url', models.URLField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicity', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('web_url', models.URLField(blank=True)),
                ('top_shop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='descriptionproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descripcion_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='products.ShopDepartment'),
        ),
    ]
