# Generated by Django 2.0.1 on 2018-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shopdepartment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
