# Generated by Django 2.0.1 on 2018-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180114_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='shopdepartment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
