# Generated by Django 2.0.1 on 2018-01-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180118_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='web_url',
            field=models.URLField(blank=True),
        ),
    ]
