# Generated by Django 2.0.1 on 2018-05-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_listwish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_ads', to='products.ShopDepartment')),
            ],
        ),
    ]
