# Generated by Django 2.0.1 on 2018-05-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_offerad_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerad',
            name='url',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
