# Generated by Django 2.0.1 on 2018-05-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
