# Generated by Django 2.0.1 on 2018-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180121_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.IntegerField(default=0),
        ),
    ]
