# Generated by Django 2.0.1 on 2018-01-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180127_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='publicity', to='products.Category'),
        ),
    ]
