# Generated by Django 2.0.1 on 2018-02-03 18:45

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180128_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descripcion_product', to='products.Product')),
            ],
        ),
    ]
