# Generated by Django 2.0.1 on 2018-02-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_descripcionproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descripcion_product', to='products.Product'),
        ),
    ]
