# Generated by Django 2.0.1 on 2018-02-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180204_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DescripcionProduct',
            new_name='DescriptionProduct',
        ),
    ]
