# Generated by Django 2.0.1 on 2018-03-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180310_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.BooleanField(default=False),
        ),
    ]
