# Generated by Django 2.0.1 on 2018-03-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_top_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='top_category',
        ),
        migrations.AddField(
            model_name='shopdepartment',
            name='top_shop',
            field=models.BooleanField(default=False),
        ),
    ]
